sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_edge.gemfile
before_install:
  - gem install bundler

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_edge.gemfile
